name: manim

on:
  push:
    paths:
      - '.github/workflows/manim.yml'
      - 'manim/**'
      # Dependencies
      - 'python-cloup/**'
      - 'python-glcontext/**'
      - 'python-manimpango/**'
      - 'python-moderngl-window/**'
      - 'python-mapbox-earcut/**'
      - 'python-pyrr/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Set up system
        run: |
          groupadd -f arch
          useradd -m -G arch -s /bin/bash manim
          pacman -Syuu --noconfirm sudo git

      - name: Install python-cloup
        working-directory: python-cloup
        run: |
          pacman -S --noconfirm \
            python-setuptools \
            python-setuptools-scm
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-glcontext
        working-directory: python-glcontext
        run: |
          pacman -S --noconfirm \
            libx11 \
            python \
            python-setuptools
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-manimpango
        working-directory: python-manimpango
        run: |
          pacman -S --noconfirm \
            cairo \
            cython \
            harfbuzz \
            pango \
            python \
            python-gobject \
            python-setuptools
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-mapbox-earcut
        working-directory: python-mapbox-earcut
        run: |
          pacman -S --noconfirm \
            cmake \
            git \
            pybind11 \
            python \
            python-pip \
            python-setuptools
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-moderngl-git (external AUR dependency)
        run: |
          pacman -S --noconfirm \
            git \
            libgl \
            python \
            python-setuptools
          git clone https://aur.archlinux.org/python-moderngl-git.git
          cd python-moderngl-git
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..

      - name: Install python-multipledispatch (external AUR dependency)
        run: |
          pacman -S --noconfirm \
            python \
            python-setuptools
          git clone https://aur.archlinux.org/python-multipledispatch.git
          cd python-multipledispatch
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..

      - name: Install python-pyrr
        working-directory: python-pyrr
        run: |
          pacman -S --noconfirm \
            python-numpy \
            python-setuptools \
            python-setuptools-scm
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-moderngl-window
        working-directory: python-moderngl-window
        run: |
          pacman -S --noconfirm \
            python-numpy \
            python-pillow \
            python-pyglet \
            python-setuptools
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-pydub (external AUR dependency)
        run: |
          pacman -S --noconfirm \
            python \
            python-setuptools
          git clone https://aur.archlinux.org/python-pydub.git
          cd python-pydub
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..

      - name: Install python-screeninfo (external AUR dependency)
        run: |
          pacman -S --noconfirm \
            python \
            python-setuptools
          git clone https://aur.archlinux.org/python-screeninfo.git
          cd python-screeninfo
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..

      - name: Install manim
        working-directory: manim
        run: |
          pacman -S --noconfirm \
            ffmpeg \
            python \
            python-cairo \
            python-click \
            python-click-default-group \
            python-colour \
            python-decorator \
            python-numpy \
            python-pillow \
            python-pygments \
            python-requests \
            python-rich \
            python-scipy \
            python-setuptools \
            python-tqdm \
            python-watchdog \
            python-networkx
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Test ManimCE
        run: |
          pacman -S --noconfirm curl
          manim render --help
          curl -L https://raw.githubusercontent.com/ManimCommunity/manim/master/example_scenes/basic.py -o basic.py
          manim basic.py SquareToCircle
