name: CI
on:
  push:
    paths:
      - 'manim/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependency
        run: |
          pacman -Tv
          pacman -Syy
          pacman --version
          groupadd -f arch
          useradd -m -G arch -s /bin/bash manim
          pacman --noconfirm -Syuu
          pacman --noconfirm -Syuu
          pacman -S --noconfirm sudo base-devel git
          chmod a=rwx $PWD/python-cloup
          chmod a=rwx $PWD/python-mapbox-earcut
          chmod a=rwx $PWD/python-manimpango
          chmod a=rwx $PWD/manim

      - name: Install python-cloup
        working-directory: python-cloup
        run: |
          pacman -S --noconfirm python-setuptools python-setuptools-scm
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-mapbox-earcut
        working-directory: python-mapbox-earcut
        run: |
          pacman -S --noconfirm cmake python-setuptools pybind11
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-moderngl-window
        working-directory: python-moderngl-window
        run: |
          chmod a=rwx $PWD
          pacman -S --noconfirm python-numpy python-pillow python-pyglet
          git clone https://aur.archlinux.org/python-moderngl-git.git
          cd python-moderngl-git
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..
          rm -rf python-moderngl-git
          git clone https://aur.archlinux.org/python-multipledispatch.git
          cd python-multipledispatch
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..
          rm -rf python-multipledispatch
          git clone https://aur.archlinux.org/python-pyrr.git
          cd python-pyrr
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..
          rm -rf python-pyrr
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-glcontext
        working-directory: python-glcontext
        run: |
          pacman -S --noconfirm python python-setuptools
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install ManimPango
        working-directory: python-manimpango
        run: |
          pacman -S --noconfirm pango cython python python-setuptools python-gobject
          su manim -c "makepkg -s"
          su manim -c "makepkg --printsrcinfo > ManimPango.SRCINFO"
          pacman -U --noconfirm *.zst

      - name: Install Deps for Manim
        run: |
          pacman -S --noconfirm \
            cmake \
            ffmpeg \
            libgl \
            python \
            python-setuptools \
            python-cairo \
            python-click \
            python-click-default-group \
            python-colour \
            python-distlib \
            python-numpy \
            python-pillow \
            python-pip \
            python-pygments \
            python-rich python-scipy \
            python-tqdm \
            python-watchdog \
            python-wheel \
            python-networkx
          git clone https://aur.archlinux.org/python-pydub.git
          cd python-pydub
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..
          rm -rf python-pydub
          git clone https://aur.archlinux.org/python-screeninfo.git
          cd python-screeninfo
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..
          rm -rf python-screeninfo

      - name: Install ManimCE
        working-directory: manim
        run: |
          su manim -c "makepkg -s"
          su manim -c "makepkg --printsrcinfo > manim.SRCINFO"
          pacman -U --noconfirm *.zst
          manim render --help
      - name: Test ManimCE
        run: |
          pacman -S --noconfirm curl
          curl -L https://raw.githubusercontent.com/ManimCommunity/manim/master/example_scenes/basic.py -o basic.py
          manim basic.py SquareToCircle
      - uses: actions/upload-artifact@v2
        with:
          name: archives
          path: |
            manim/*.zst
            python-manimpango/*.zst
      - uses: actions/upload-artifact@v2
        with:
          name: source-info
          path: |
            manim/*.SRCINFO
            python-manimpango/*.SRCINFO

