name: python-glcontext

on:
  push:
    paths:
      - '.github/workflows/python-glcontext.yml'
      - 'pkginstall.sh'
      - 'python-glcontext/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Set up system
        run: |
          groupadd -f arch
          useradd -m -G arch -s /bin/bash manim
          pacman -Syuu --noconfirm sudo git

      - name: Install python-glcontext
        working-directory: python-glcontext
        run: |
          ../pkginstall.sh user=manim pkg=python-glcontext
