name: python-glcontext

on:
  push:
    paths:
      - '.github/workflows/python-glcontext.yml'
      - 'python-glcontext/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Set up system
        run: |
          groupadd -f arch
          useradd -m -G arch -s /bin/bash manim
          pacman -Syuu --noconfirm sudo git pacman-contrib

      - name: Install python-glcontext
        working-directory: python-glcontext
        run: |
          pacman -S --noconfirm \
            libx11 \
            python \
            python-setuptools
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
