name: python-glcontext

on:
  push:
    paths:
      - '.github/workflows/python-glcontext.yml'
      - 'pkginstall.sh'
      - 'python-glcontext/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install python-glcontext
        working-directory: python-glcontext
        run: |
          ../pkginstall.sh user=groctel pkg=python-glcontext
