name: python-pyrr

on:
  push:
    paths:
      - '.github/workflows/python-pyrr.yml'
      - 'pkginstall.sh'
      - 'python-pyrr/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install python-cloup
        working-directory: python-cloup
        run: |
          ../pkginstall.sh user=manim pkg=python-pyrr
