name: python-moderngl-window

on:
  push:
    paths:
      - '.github/workflows/python-moderngl-window.yml'
      - 'python-moderngl-window/**'
      # Dependencies
      - 'python-pyrr/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Set up system
        run: |
          groupadd -f arch
          useradd -m -G arch -s /bin/bash manim
          pacman -Syuu --noconfirm sudo git pacman-contrib

      - name: Install python-moderngl-git (external AUR dependency)
        run: |
          pacman -S --noconfirm \
            git \
            libgl \
            python \
            python-setuptools
          git clone https://aur.archlinux.org/python-moderngl-git.git
          cd python-moderngl-git
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..

      - name: Install python-multipledispatch (external AUR dependency)
        run: |
          pacman -S --noconfirm \
            python \
            python-setuptools
          git clone https://aur.archlinux.org/python-multipledispatch.git
          cd python-multipledispatch
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd ..

      - name: Install python-pyrr
        working-directory: python-pyrr
        run: |
          pacman -S --noconfirm \
            python-setuptools \
            python-setuptools-scm
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install python-moderngl-window
        working-directory: python-moderngl-window
        run: |
          pacman -S --noconfirm \
            python-setuptools \
            python-setuptools-scm
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
