name: python-mapbox-earcut

on:
  push:
    paths:
      - '.github/workflows/python-mapbox-earcut.yml'
      - 'pkginstall.sh'
      - 'python-mapbox-earcut/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install python-mapbox-earcut
        working-directory: python-mapbox-earcut
        run: |
          ../pkginstall.sh user=manim pkg=python-mapbox-earcut
