name: python-cloup

on:
  push:
    paths:
      - 'python-cloup/**'
      - '.github/workflows/python-cloup.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - name: Set up pacman
        run: |
          groupadd -f arch
          useradd -m -G arch -s /bin/bash manim
          pacman --noconfirm -Syuu
          pacman -S --noconfirm sudo base base-devel git pacman-contrib
          chmod a=rwx $PWD/python-cloup

      - name: Install python-cloup
        working-directory: python-cloup
        run: |
          pacman -S --noconfirm \
            python-setuptools \
            python-setuptools-scm
          su manim -c "makepkg --printsrcinfo > .SRCINFO; makepkg -s"
          pacman -U --noconfirm *.zst
