name: python-cloup

on:
  push:
    paths:
      - '.github/workflows/python-cloup.yml'
      - 'pkginstall.sh'
      - 'python-cloup/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2


      - name: Install python-cloup
        working-directory: python-cloup
        run: |
          ../pkginstall.sh user=manim pkg=python-cloup
