name: python-cloup installation test

on:
  push:
    paths:
      - 'python-cloup/**'

jobs:
  installation-test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - name: Set up pacman
        run: |
          groupadd -f arch
          useradd -m -G arch -s /bin/bash manim
          pacman --noconfirm -Syuu
          pacman -S --noconfirm sudo base base-devel git pacman-contrib

      - name: Install python-cloup
        working-directory: python-cloup
        run: |
          pacman -S --noconfirm \
            python-setuptools \
            python-setuptools-scm
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          makepkg --printsrcinfo > .SRCINFO;

      - uses: actions/upload-artifact@v2
        with:
          name: archives
          path: |
            manim/*.zst
            python-manimpango/*.zst
      - uses: actions/upload-artifact@v2
        with:
          name: source-info
          path: |
            manim/*.SRCINFO
            python-manimpango/*.SRCINFO
