name: python-manimpango

on:
  push:
    paths:
      - '.github/workflows/python-manimpango.yml'
      - 'pkginstall.sh'
      - 'python-manimpango/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2


      - name: Install python-manimpango
        working-directory: python-manimpango
        run: |
          ../pkginstall.sh user=groctel pkg=python-manimpango
