name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependency
        run: |
          pacman -Tv
          pacman -Syy
          pacman --version
          groupadd -f arch
          useradd -m -G arch -s /bin/bash manim
          pacman --noconfirm -Syuu
          pacman --noconfirm -Syuu
          pacman -S --noconfirm sudo base-devel git
          chmod a=rwx $PWD/python-manimpango
          chmod a=rwx $PWD/manim-community

      - name: Install ManimPango
        working-directory: python-manimpango
        run: |
          pacman -S --noconfirm pango cython python python-setuptools
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst

      - name: Install Deps for Manim
        run: |
          pacman -S --noconfirm \
            cmake \
            ffmpeg \
            python \
            python-setuptools \
            python-cairo \
            python-colour \
            python-distlib \
            python-networkx \
            python-numpy \
            python-pillow \
            python-pip \
            python-pygments \
            python-rich python-scipy \
            python-tqdm \
            python-wheel
          cd $TMP
          git clone https://aur.archlinux.org/python-pydub.git
          cd python-pydub
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd $TMP
          git clone https://aur.archlinux.org/python-cloup.git
          cd python-cloup
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd $TMP
          git clone https://aur.archlinux.org/packages/python-mapbox-earcut/
          cd python-mapbox-earcut
          chmod a=rwx $PWD
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          cd $TMP

      - name: Install ManimCE
        working-directory: manim-community
        run: |
          su manim -c "makepkg -s"
          pacman -U --noconfirm *.zst
          manim -h
      - name: Test ManimCE
        run: |
          pacman -S --noconfirm curl
          curl -L https://raw.githubusercontent.com/ManimCommunity/manim/master/example_scenes/basic.py -o basic.py
          manim basic.py SquareToCircle
      - uses: actions/upload-artifact@v2
        with:
          name: archives
          path: |
            manim-community/*.zst
            python-manimpango/*.zst
