name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ManimPango
        working-directory: python-manimpango
        run: |
          makepkg -si
      - name: Install ManimCE
        working-directory: manimce
        run: |
          makepkg -si
      
