name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependency
        working-directory: python-manimpango
        run: |
          groupadd -f arch
          useradd -m -G arch -s /bin/bash manim
          pacman --noconfirm -Syuu
          pacman --noconfirm -Syuu
          pacman -S sudo base-devel
          chmod a=rwx $PWD/python-manimpango
      - name: Install ManimPango
        working-directory: python-manimpango
        run: |
          su manim -c "makepkg -si"
      - name: Install ManimCE
        working-directory: manimce
        run: |
          su manim -c "makepkg -si"
      
